// Pure seed data for CineGraph — separated from the runner script for readability.
// This dataset uses real, well-known Bollywood and Tollywood (Telugu cinema)
// films, actors, and directors. Titles, years, directors, and lead cast are
// drawn from well-documented, widely known facts. A few studio-to-film
// production credits are approximate/illustrative rather than verified —
// this is seed data for a graph-database demo, not an authoritative
// filmography, so double-check any specific credit before relying on it.

const genres = [
  { id: "g1", name: "Drama" },
  { id: "g2", name: "Romance" },
  { id: "g3", name: "Action" },
  { id: "g4", name: "Comedy" },
  { id: "g5", name: "Musical" },
  { id: "g6", name: "Thriller" },
  { id: "g7", name: "Sports" },
  { id: "g8", name: "Family" },
  { id: "g9", name: "Fantasy" },
  { id: "g10", name: "Crime" },
];

const studios = [
  { id: "st1", name: "Yash Raj Films" },
  { id: "st2", name: "Dharma Productions" },
  { id: "st3", name: "UTV Motion Pictures" },
  { id: "st4", name: "Excel Entertainment" },
  { id: "st5", name: "Arka Media Works" },
  { id: "st6", name: "Mythri Movie Makers" },
  { id: "st7", name: "Geetha Arts" },
];

const directors = [
  { id: "d1", name: "Aditya Chopra" },
  { id: "d2", name: "Ashutosh Gowariker" },
  { id: "d3", name: "Rajkumar Hirani" },
  { id: "d4", name: "Zoya Akhtar" },
  { id: "d5", name: "Nitesh Tiwari" },
  { id: "d6", name: "Vikas Bahl" },
  { id: "d7", name: "Sriram Raghavan" },
  { id: "d8", name: "Aniruddha Roy Chowdhury" },
  { id: "d9", name: "Anurag Basu" },
  { id: "d10", name: "Karan Johar" },
  { id: "d11", name: "Rakeysh Omprakash Mehra" },
  { id: "d12", name: "Shimit Amin" },
  { id: "d13", name: "Shoojit Sircar" },
  { id: "d14", name: "S. S. Rajamouli" },
  { id: "d15", name: "Sandeep Reddy Vanga" },
  { id: "d16", name: "Sukumar" },
  { id: "d17", name: "Trivikram Srinivas" },
  { id: "d18", name: "Surender Reddy" },
  { id: "d19", name: "Parasuram Petla" },
  { id: "d20", name: "Puri Jagannadh" },
];

const actors = [
  { id: "a1", name: "Shah Rukh Khan", birthYear: 1965 },
  { id: "a2", name: "Kajol", birthYear: 1974 },
  { id: "a3", name: "Aamir Khan", birthYear: 1965 },
  { id: "a4", name: "R. Madhavan", birthYear: 1970 },
  { id: "a5", name: "Sharman Joshi", birthYear: 1978 },
  { id: "a6", name: "Boman Irani", birthYear: 1959 },
  { id: "a7", name: "Hrithik Roshan", birthYear: 1974 },
  { id: "a8", name: "Farhan Akhtar", birthYear: 1974 },
  { id: "a9", name: "Abhay Deol", birthYear: 1976 },
  { id: "a10", name: "Katrina Kaif", birthYear: 1983 },
  { id: "a11", name: "Ranveer Singh", birthYear: 1985 },
  { id: "a12", name: "Alia Bhatt", birthYear: 1993 },
  { id: "a13", name: "Fatima Sana Shaikh", birthYear: 1992 },
  { id: "a14", name: "Sanya Malhotra", birthYear: 1992 },
  { id: "a15", name: "Kangana Ranaut", birthYear: 1987 },
  { id: "a16", name: "Ayushmann Khurrana", birthYear: 1984 },
  { id: "a17", name: "Tabu", birthYear: 1971 },
  { id: "a18", name: "Radhika Apte", birthYear: 1985 },
  { id: "a19", name: "Amitabh Bachchan", birthYear: 1942 },
  { id: "a20", name: "Taapsee Pannu", birthYear: 1987 },
  { id: "a21", name: "Ranbir Kapoor", birthYear: 1982 },
  { id: "a22", name: "Priyanka Chopra", birthYear: 1982 },
  { id: "a23", name: "Ileana D'Cruz", birthYear: 1987 },
  { id: "a24", name: "Siddharth", birthYear: 1979 },
  { id: "a25", name: "Deepika Padukone", birthYear: 1986 },
  { id: "a26", name: "Irrfan Khan", birthYear: 1967 },
  { id: "a27", name: "Prabhas", birthYear: 1979 },
  { id: "a28", name: "Rana Daggubati", birthYear: 1984 },
  { id: "a29", name: "Anushka Shetty", birthYear: 1981 },
  { id: "a30", name: "Tamannaah", birthYear: 1989 },
  { id: "a31", name: "Vijay Deverakonda", birthYear: 1989 },
  { id: "a32", name: "Shalini Pandey", birthYear: 1993 },
  { id: "a33", name: "Allu Arjun", birthYear: 1983 },
  { id: "a34", name: "Rashmika Mandanna", birthYear: 1996 },
  { id: "a35", name: "N. T. Rama Rao Jr.", birthYear: 1983 },
  { id: "a36", name: "Ram Charan", birthYear: 1985 },
  { id: "a37", name: "Ajay Devgn", birthYear: 1969 },
  { id: "a38", name: "Samantha Ruth Prabhu", birthYear: 1987 },
  { id: "a39", name: "Kajal Aggarwal", birthYear: 1985 },
  { id: "a40", name: "Pooja Hegde", birthYear: 1990 },
  { id: "a41", name: "Nani", birthYear: 1984 },
  { id: "a42", name: "Sudeep", birthYear: 1971 },
  { id: "a43", name: "Chiranjeevi", birthYear: 1955 },
  { id: "a44", name: "Nayanthara", birthYear: 1984 },
  { id: "a45", name: "Mahesh Babu", birthYear: 1975 },
];

const movies = [
  { id: "m1", title: "Dilwale Dulhania Le Jayenge", releaseYear: 1995, rating: 8.0, description: "Two young NRIs fall in love on a European trip, then fight for that love back home in Punjab.", directorId: "d1", studioId: "st1", genreIds: ["g2", "g1"], actorIds: ["a1", "a2"] },
  { id: "m2", title: "Lagaan", releaseYear: 2001, rating: 8.1, description: "Villagers under colonial rule wager their tax burden on the outcome of a cricket match.", directorId: "d2", studioId: "st3", genreIds: ["g7", "g1", "g5"], actorIds: ["a3"] },
  { id: "m3", title: "3 Idiots", releaseYear: 2009, rating: 8.4, description: "Two friends search for their long-lost engineering-college roommate, unraveling his unconventional legacy.", directorId: "d3", studioId: "st3", genreIds: ["g4", "g1"], actorIds: ["a3", "a4", "a5", "a6"] },
  { id: "m4", title: "Zindagi Na Milegi Dobara", releaseYear: 2011, rating: 8.1, description: "Three friends confront old fears and unfinished business on a bachelor road trip through Spain.", directorId: "d4", studioId: "st4", genreIds: ["g1", "g4"], actorIds: ["a7", "a8", "a9", "a10"] },
  { id: "m5", title: "Gully Boy", releaseYear: 2019, rating: 7.9, description: "A young man from Mumbai's slums finds his voice through underground rap.", directorId: "d4", studioId: "st4", genreIds: ["g1", "g5"], actorIds: ["a11", "a12"] },
  { id: "m6", title: "Dangal", releaseYear: 2016, rating: 8.4, description: "A former wrestler trains his daughters to become India's first world-class female wrestlers.", directorId: "d5", studioId: "st3", genreIds: ["g7", "g1"], actorIds: ["a3", "a13", "a14"] },
  { id: "m7", title: "Queen", releaseYear: 2013, rating: 8.2, description: "Jilted days before her wedding, a young woman takes her honeymoon alone and discovers herself.", directorId: "d6", studioId: "st2", genreIds: ["g4", "g1"], actorIds: ["a15"] },
  { id: "m8", title: "Andhadhun", releaseYear: 2018, rating: 8.2, description: "A blind pianist becomes an accidental witness to a murder, blurring the line between deception and survival.", directorId: "d7", studioId: "st3", genreIds: ["g6", "g10", "g4"], actorIds: ["a16", "a17", "a18"] },
  { id: "m9", title: "Pink", releaseYear: 2016, rating: 8.1, description: "A retired lawyer defends three young women against a campaign to discredit them after a violent altercation.", directorId: "d8", studioId: "st2", genreIds: ["g1", "g6"], actorIds: ["a19", "a20"] },
  { id: "m10", title: "Barfi!", releaseYear: 2012, rating: 8.1, description: "A deaf-mute man's playful romance with two very different women unfolds in 1970s Darjeeling.", directorId: "d9", studioId: "st3", genreIds: ["g2", "g1", "g4"], actorIds: ["a21", "a22", "a23"] },
  { id: "m11", title: "Kabhi Khushi Kabhie Gham", releaseYear: 2001, rating: 7.4, description: "A wealthy family fractures when the adopted elder son marries outside his class, and years later must reunite.", directorId: "d10", studioId: "st2", genreIds: ["g1", "g8", "g5"], actorIds: ["a1", "a2", "a19", "a7"] },
  { id: "m12", title: "Rang De Basanti", releaseYear: 2006, rating: 8.1, description: "A documentary shoot pulls a group of disillusioned college friends into political awakening and action.", directorId: "d11", studioId: "st3", genreIds: ["g1"], actorIds: ["a3", "a24", "a4"] },
  { id: "m13", title: "Swades", releaseYear: 2004, rating: 8.2, description: "A NASA scientist returns to his ancestral village and confronts what home and duty really mean.", directorId: "d2", studioId: "st3", genreIds: ["g1"], actorIds: ["a1"] },
  { id: "m14", title: "Chak De! India", releaseYear: 2007, rating: 8.0, description: "A disgraced former hockey captain coaches the women's national team toward redemption.", directorId: "d12", studioId: "st1", genreIds: ["g7", "g1"], actorIds: ["a1"] },
  { id: "m15", title: "Piku", releaseYear: 2015, rating: 7.6, description: "A short road trip with her aging, hypochondriac father tests a young woman's patience and devotion.", directorId: "d13", studioId: "st2", genreIds: ["g4", "g1"], actorIds: ["a25", "a19", "a26"] },
  { id: "m16", title: "Baahubali: The Beginning", releaseYear: 2015, rating: 8.0, description: "A young man raised in a waterfall village uncovers his royal destiny and a kingdom's buried past.", directorId: "d14", studioId: "st5", genreIds: ["g3", "g9"], actorIds: ["a27", "a28", "a29", "a30"] },
  { id: "m17", title: "Baahubali 2: The Conclusion", releaseYear: 2017, rating: 8.2, description: "The saga concludes with the answer to why Kattappa killed Baahubali, and the fight to reclaim a throne.", directorId: "d14", studioId: "st5", genreIds: ["g3", "g9"], actorIds: ["a27", "a28", "a29", "a30"] },
  { id: "m18", title: "RRR", releaseYear: 2022, rating: 7.9, description: "Two real-life revolutionaries meet in a fictional friendship forged before their fight against colonial rule.", directorId: "d14", studioId: "st6", genreIds: ["g3", "g1"], actorIds: ["a35", "a36", "a12", "a37"] },
  { id: "m19", title: "Arjun Reddy", releaseYear: 2017, rating: 8.1, description: "A brilliant, short-tempered surgeon spirals into self-destruction after losing the woman he loves.", directorId: "d15", studioId: "st7", genreIds: ["g2", "g1"], actorIds: ["a31", "a32"] },
  { id: "m20", title: "Pushpa: The Rise", releaseYear: 2021, rating: 7.6, description: "A laborer rises through the ranks of a red sandalwood smuggling syndicate through sheer will.", directorId: "d16", studioId: "st6", genreIds: ["g3", "g1"], actorIds: ["a33", "a34"] },
  { id: "m21", title: "Ala Vaikunthapurramuloo", releaseYear: 2020, rating: 7.4, description: "A young man discovers he was switched at birth and must reclaim his place in his real family.", directorId: "d17", studioId: "st7", genreIds: ["g8", "g3", "g4"], actorIds: ["a33", "a40"] },
  { id: "m22", title: "Rangasthalam", releaseYear: 2018, rating: 8.2, description: "A hearing-impaired villager takes on a corrupt local power structure to avenge his brother.", directorId: "d16", studioId: "st6", genreIds: ["g1", "g3"], actorIds: ["a36", "a38"] },
  { id: "m23", title: "Magadheera", releaseYear: 2009, rating: 7.4, description: "A modern-day biker discovers his past-life bond with a warrior princess spans four centuries.", directorId: "d14", studioId: "st7", genreIds: ["g3", "g9", "g2"], actorIds: ["a36", "a39"] },
  { id: "m24", title: "Eega", releaseYear: 2012, rating: 7.4, description: "A murdered man is reincarnated as a housefly and sets out to protect the woman he loved.", directorId: "d14", studioId: "st7", genreIds: ["g9", "g3", "g4"], actorIds: ["a41", "a38", "a42"] },
  { id: "m25", title: "Sye Raa Narasimha Reddy", releaseYear: 2019, rating: 7.3, description: "A tribal chieftain leads an armed uprising against colonial rule decades before the 1857 revolt.", directorId: "d18", studioId: "st6", genreIds: ["g3", "g1"], actorIds: ["a43", "a44"] },
  { id: "m26", title: "Geetha Govindam", releaseYear: 2018, rating: 7.6, description: "A misunderstanding on a train sets off a slow-burn romance between two mismatched strangers.", directorId: "d19", studioId: "st7", genreIds: ["g2", "g4"], actorIds: ["a31", "a34"] },
  { id: "m27", title: "Pokiri", releaseYear: 2006, rating: 7.9, description: "An undercover cop poses as a small-time gangster to infiltrate a criminal network from within.", directorId: "d20", studioId: "st6", genreIds: ["g3", "g6"], actorIds: ["a45", "a23"] },
  { id: "m28", title: "Businessman", releaseYear: 2012, rating: 7.3, description: "A criminal mastermind builds a citywide extortion racket run with corporate-style precision.", directorId: "d20", studioId: "st6", genreIds: ["g3", "g10"], actorIds: ["a45", "a39"] },
];

module.exports = { genres, studios, directors, actors, movies };






// // Pure seed data for CineGraph — separated from the runner script for readability.
// // All entities are fictional (invented titles/names) to keep this a clean,
// // self-contained demo dataset with no real-world attribution concerns.

// const genres = [
//   { id: "g1", name: "Action" },
//   { id: "g2", name: "Drama" },
//   { id: "g3", name: "Sci-Fi" },
//   { id: "g4", name: "Comedy" },
//   { id: "g5", name: "Thriller" },
//   { id: "g6", name: "Romance" },
//   { id: "g7", name: "Fantasy" },
//   { id: "g8", name: "Horror" },
//   { id: "g9", name: "Mystery" },
//   { id: "g10", name: "Animation" },
// ];

// const studios = [
//   { id: "st1", name: "Northstar Pictures" },
//   { id: "st2", name: "Ember Road Films" },
//   { id: "st3", name: "BluePeak Studios" },
//   { id: "st4", name: "Horizon Line Entertainment" },
//   { id: "st5", name: "Copper Lantern Films" },
//   { id: "st6", name: "Vantage Point Studios" },
//   { id: "st7", name: "Driftwood Media" },
// ];

// const directors = [
//   { id: "d1", name: "Maren Castillo" },
//   { id: "d2", name: "Theo Whitfield" },
//   { id: "d3", name: "Priya Anand" },
//   { id: "d4", name: "Jonas Ellery" },
//   { id: "d5", name: "Sofia Marchetti" },
//   { id: "d6", name: "Elliot Brandt" },
//   { id: "d7", name: "Naomi Voss" },
//   { id: "d8", name: "Callum Reyes" },
//   { id: "d9", name: "Iris Nakamura" },
//   { id: "d10", name: "Victor Solano" },
//   { id: "d11", name: "Freya Lindqvist" },
//   { id: "d12", name: "Marcus Odell" },
//   { id: "d13", name: "Lena Kovac" },
//   { id: "d14", name: "Dmitri Orlov" },
//   { id: "d15", name: "Ana Beaumont" },
// ];

// const actors = [
//   { id: "a1", name: "Nova Ashford", birthYear: 1988 },
//   { id: "a2", name: "Silas Vance", birthYear: 1979 },
//   { id: "a3", name: "Wren Callahan", birthYear: 1990 },
//   { id: "a4", name: "Beatrix Solene", birthYear: 1985 },
//   { id: "a5", name: "Julian Marchetti", birthYear: 1975 },
//   { id: "a6", name: "Odette Farrow", birthYear: 1993 },
//   { id: "a7", name: "Gideon Marsh", birthYear: 1982 },
//   { id: "a8", name: "Ines Bellamy", birthYear: 1991 },
//   { id: "a9", name: "Rafael Odom", birthYear: 1978 },
//   { id: "a10", name: "Talia Sinclair", birthYear: 1989 },
//   { id: "a11", name: "Milo Thackeray", birthYear: 1986 },
//   { id: "a12", name: "Coraline Ashby", birthYear: 1994 },
//   { id: "a13", name: "Desmond Rourke", birthYear: 1980 },
//   { id: "a14", name: "Yara Delacroix", birthYear: 1992 },
//   { id: "a15", name: "Atticus Grey", birthYear: 1983 },
//   { id: "a16", name: "Selene Vargas", birthYear: 1987 },
//   { id: "a17", name: "Emrys Caldwell", birthYear: 1976 },
//   { id: "a18", name: "Marisol Quinn", birthYear: 1990 },
//   { id: "a19", name: "Tobias Renfrew", birthYear: 1984 },
//   { id: "a20", name: "Aurelia Stone", birthYear: 1993 },
//   { id: "a21", name: "Cassius Whitlock", birthYear: 1981 },
//   { id: "a22", name: "Ophelia Brandt", birthYear: 1988 },
//   { id: "a23", name: "Nikolai Voss", birthYear: 1977 },
//   { id: "a24", name: "Ivy Callahan", birthYear: 1995 },
//   { id: "a25", name: "Barnaby Fitch", birthYear: 1985 },
//   { id: "a26", name: "Rosalind Marchetti", birthYear: 1990 },
//   { id: "a27", name: "Dashiell Kane", birthYear: 1979 },
//   { id: "a28", name: "Wilhelmina Cross", birthYear: 1986 },
//   { id: "a29", name: "Percival Lang", birthYear: 1974 },
//   { id: "a30", name: "Seraphina Woods", birthYear: 1992 },
//   { id: "a31", name: "Ezekiel Thorne", birthYear: 1982 },
//   { id: "a32", name: "Marguerite Delvaux", birthYear: 1989 },
//   { id: "a33", name: "Ambrose Finch", birthYear: 1980 },
//   { id: "a34", name: "Clementine Reyes", birthYear: 1994 },
//   { id: "a35", name: "Thaddeus Wren", birthYear: 1978 },
//   { id: "a36", name: "Isolde Marchbanks", birthYear: 1987 },
//   { id: "a37", name: "Orson Blackwood", birthYear: 1983 },
//   { id: "a38", name: "Vesper Callahan", birthYear: 1991 },
//   { id: "a39", name: "Leopold Sterling", birthYear: 1976 },
//   { id: "a40", name: "Genevieve Ashcroft", birthYear: 1990 },
// ];

// const movies = [
//   { id: "m1", title: "Silent Horizon", releaseYear: 2015, rating: 7.8, description: "A stranded astronaut fights to survive on a dying space station.", directorId: "d1", studioId: "st1", genreIds: ["g3", "g5"], actorIds: ["a1", "a2", "a3", "a4"] },
//   { id: "m2", title: "Ashes of Meridian", releaseYear: 2016, rating: 7.2, description: "A detective uncovers a conspiracy tying together three unsolved murders.", directorId: "d2", studioId: "st2", genreIds: ["g5", "g9"], actorIds: ["a5", "a6", "a7", "a8"] },
//   { id: "m3", title: "The Gilded Hour", releaseYear: 2014, rating: 6.9, description: "A jazz pianist in a fading dance hall navigates love and ambition.", directorId: "d3", studioId: "st3", genreIds: ["g2", "g6"], actorIds: ["a9", "a10", "a11", "a12"] },
//   { id: "m4", title: "Wolves of Kestrel Pass", releaseYear: 2017, rating: 8.1, description: "Two rival smugglers form an uneasy alliance to survive a mountain winter.", directorId: "d4", studioId: "st1", genreIds: ["g1", "g2"], actorIds: ["a1", "a13", "a14", "a15"] },
//   { id: "m5", title: "Paper Lanterns", releaseYear: 2013, rating: 7.0, description: "A grieving widow rebuilds her life in a small coastal town.", directorId: "d5", studioId: "st4", genreIds: ["g2", "g6"], actorIds: ["a16", "a17", "a18", "a2"] },
//   { id: "m6", title: "Static Bloom", releaseYear: 2018, rating: 6.5, description: "A group of hackers accidentally trigger a citywide blackout.", directorId: "d6", studioId: "st5", genreIds: ["g5", "g3"], actorIds: ["a19", "a20", "a3", "a21"] },
//   { id: "m7", title: "The Cartographer's Daughter", releaseYear: 2012, rating: 7.6, description: "An explorer's daughter continues his search for a lost city.", directorId: "d7", studioId: "st2", genreIds: ["g1", "g7"], actorIds: ["a22", "a23", "a5", "a24"] },
//   { id: "m8", title: "Midnight Carousel", releaseYear: 2019, rating: 6.8, description: "A traveling circus hides a dark secret from its newest performer.", directorId: "d8", studioId: "st6", genreIds: ["g8", "g9"], actorIds: ["a25", "a26", "a6", "a27"] },
//   { id: "m9", title: "Ember and Iron", releaseYear: 2016, rating: 7.9, description: "A blacksmith's apprentice discovers she's the last of a forgotten order.", directorId: "d9", studioId: "st1", genreIds: ["g7", "g1"], actorIds: ["a1", "a28", "a29", "a4"] },
//   { id: "m10", title: "Low Tide", releaseYear: 2011, rating: 6.3, description: "A fisherman's family confronts old secrets during a coastal storm.", directorId: "d10", studioId: "st4", genreIds: ["g2", "g5"], actorIds: ["a16", "a30", "a31", "a17"] },
//   { id: "m11", title: "The Quiet Frequency", releaseYear: 2020, rating: 7.4, description: "A radio operator intercepts a signal that shouldn't exist.", directorId: "d1", studioId: "st3", genreIds: ["g3", "g9"], actorIds: ["a2", "a32", "a33", "a3"] },
//   { id: "m12", title: "Vermilion Nights", releaseYear: 2015, rating: 6.7, description: "Two con artists fall for each other while running the same scheme.", directorId: "d11", studioId: "st5", genreIds: ["g6", "g4"], actorIds: ["a34", "a35", "a9", "a36"] },
//   { id: "m13", title: "Fields of Amaranth", releaseYear: 2014, rating: 7.1, description: "A farming family struggles to hold onto their land during a drought.", directorId: "d3", studioId: "st7", genreIds: ["g2"], actorIds: ["a10", "a37", "a38", "a11"] },
//   { id: "m14", title: "The Last Cartridge", releaseYear: 2017, rating: 7.7, description: "A retired soldier is pulled back into one final mission.", directorId: "d12", studioId: "st2", genreIds: ["g1", "g5"], actorIds: ["a22", "a39", "a40", "a23"] },
//   { id: "m15", title: "Hollow Constellations", releaseYear: 2021, rating: 8.0, description: "A physicist races to prove a discovery that could rewrite cosmology.", directorId: "d1", studioId: "st1", genreIds: ["g3", "g2"], actorIds: ["a1", "a2", "a20", "a4"] },
//   { id: "m16", title: "The Painter's Ghost", releaseYear: 2013, rating: 6.6, description: "An art restorer becomes convinced a haunted painting is trying to communicate.", directorId: "d13", studioId: "st6", genreIds: ["g8", "g9"], actorIds: ["a25", "a6", "a27", "a26"] },
//   { id: "m17", title: "Redline Serenade", releaseYear: 2018, rating: 7.3, description: "Underground street racers navigate loyalty and betrayal.", directorId: "d6", studioId: "st5", genreIds: ["g1", "g4"], actorIds: ["a19", "a21", "a3", "a35"] },
//   { id: "m18", title: "The Orchard Keeper", releaseYear: 2012, rating: 7.5, description: "A reclusive orchard owner mentors a runaway teenager.", directorId: "d5", studioId: "st4", genreIds: ["g2"], actorIds: ["a16", "a17", "a18", "a30"] },
//   { id: "m19", title: "Salt and Static", releaseYear: 2019, rating: 6.4, description: "A marine biologist and a fisherman clash over a dying reef.", directorId: "d10", studioId: "st1", genreIds: ["g2", "g6"], actorIds: ["a31", "a1", "a17", "a4"] },
//   { id: "m20", title: "The Cipher Room", releaseYear: 2020, rating: 7.8, description: "Codebreakers race against time during a tense standoff.", directorId: "d2", studioId: "st2", genreIds: ["g5", "g9"], actorIds: ["a5", "a8", "a22", "a24"] },
//   { id: "m21", title: "Wildfire Season", releaseYear: 2016, rating: 6.9, description: "A firefighting crew battles a blaze that hides a case of arson.", directorId: "d14", studioId: "st3", genreIds: ["g1", "g5"], actorIds: ["a33", "a32", "a2", "a20"] },
//   { id: "m22", title: "The Marionette's Waltz", releaseYear: 2015, rating: 6.8, description: "A puppeteer's creations seem to move on their own.", directorId: "d8", studioId: "st6", genreIds: ["g8", "g10"], actorIds: ["a25", "a27", "a6", "a36"] },
//   { id: "m23", title: "Coastal Static", releaseYear: 2014, rating: 7.0, description: "A radio DJ becomes the last voice broadcasting during a hurricane.", directorId: "d1", studioId: "st1", genreIds: ["g5", "g2"], actorIds: ["a2", "a3", "a4", "a1"] },
//   { id: "m24", title: "The Longest Winter Road", releaseYear: 2011, rating: 7.2, description: "A trucking family fights to keep their business alive.", directorId: "d15", studioId: "st4", genreIds: ["g2"], actorIds: ["a37", "a38", "a10", "a13"] },
//   { id: "m25", title: "Faultlines", releaseYear: 2022, rating: 8.2, description: "A seismologist predicts a catastrophic quake no one believes is coming.", directorId: "d1", studioId: "st1", genreIds: ["g5", "g3"], actorIds: ["a1", "a2", "a20", "a33"] },
//   { id: "m26", title: "The Understudy", releaseYear: 2013, rating: 6.5, description: "A theater understudy's ambition spirals into obsession.", directorId: "d9", studioId: "st5", genreIds: ["g5", "g9"], actorIds: ["a28", "a29", "a34", "a9"] },
//   { id: "m27", title: "Harbor Lights", releaseYear: 2017, rating: 7.6, description: "Two estranged sisters reunite to save their father's shipyard.", directorId: "d5", studioId: "st4", genreIds: ["g2", "g6"], actorIds: ["a16", "a18", "a30", "a31"] },
//   { id: "m28", title: "The Glass Orchard", releaseYear: 2019, rating: 6.7, description: "A scientist's greenhouse experiment threatens to overrun the town.", directorId: "d3", studioId: "st3", genreIds: ["g3", "g8"], actorIds: ["a10", "a11", "a37", "a12"] },
//   { id: "m29", title: "Nightfall Overture", releaseYear: 2021, rating: 7.9, description: "A composer's final symphony seems tied to a string of disappearances.", directorId: "d13", studioId: "st6", genreIds: ["g9", "g8"], actorIds: ["a25", "a26", "a6", "a29"] },
//   { id: "m30", title: "Terminal Velocity", releaseYear: 2018, rating: 7.1, description: "A stunt pilot is drawn into an international smuggling ring.", directorId: "d12", studioId: "st2", genreIds: ["g1", "g5"], actorIds: ["a22", "a39", "a5", "a23"] },
// ];

// module.exports = { genres, studios, directors, actors, movies };
